// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SimpleSongs;

namespace SimpleSongs.Migrations
{
    [DbContext(typeof(SimpleSongsDbContext))]
    [Migration("20211004113637_FirstMigration")]
    partial class FirstMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SimpleSongs.Model.Song", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AlbumName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Author")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Length")
                        .HasColumnType("float");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Songs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AlbumName = "Fankomat",
                            Author = "Blenders",
                            Length = 220.0,
                            Title = "Ciągnik"
                        },
                        new
                        {
                            Id = 2,
                            AlbumName = "MOON EP",
                            Author = "M.O.O.N.",
                            Length = 271.0,
                            Title = "Hydrogen"
                        },
                        new
                        {
                            Id = 3,
                            AlbumName = "...Baby One More Time",
                            Author = "Britney Spears",
                            Length = 210.0,
                            Title = "...Baby One More Time"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
